const preview = (id, labels) => labels.map((label) => `evidence/${id}-${label}.webp`);
const pdf = (id) => `evidence/pdfs/${id}.pdf`;

export const documentTypes = [
  ["certificate", "Certificate"],
  ["type-test", "Type Test"],
  ["test-report", "Test Report"],
  ["ce-verification", "CE Verification"],
  ["efficiency-report", "Efficiency Report"],
  ["drawing", "Engineering Drawing"],
  ["factory-document", "Factory Document"]
];

export const documents = [
  {
    id: "oil-distribution-1600kva-tuv",
    title: "1600 kVA 22 kV TÜV Certificate of Conformity",
    type: "certificate",
    productIds: ["oil-immersed-distribution-transformer"],
    issuer: "TÜV Rheinland",
    reportNo: "AK 50683814 0001",
    testedModel: "S-M-1600/22-Tier2",
    ratedPower: "1600 kVA",
    ratedVoltage: "22 / 0.42 kV",
    standards: [],
    previewImages: preview("oil-distribution-1600kva-tuv", ["cover"]),
    pdf: pdf("oil-distribution-1600kva-tuv"),
    featured: true,
    tags: ["TÜV", "CERTIFICATE"],
    voltage: "22 kV"
  },
  {
    id: "oil-distribution-1600kva-type-test",
    title: "1600 kVA 22 kV Complete Type Test Report",
    type: "type-test",
    productIds: ["oil-immersed-distribution-transformer"],
    issuer: "TÜV Rheinland",
    reportNo: "CN25ZJN4 001",
    testedModel: "S-M-1600/22-Tier2",
    ratedPower: "1600 kVA",
    ratedVoltage: "22 / 0.42 kV",
    standards: ["IEC 60076 series"],
    previewImages: preview("oil-distribution-1600kva-type-test", ["cover", "summary", "parameters", "product-photo"]),
    pdf: pdf("oil-distribution-1600kva-type-test"),
    featured: true,
    tags: ["TYPE TEST", "IEC", "TÜV"],
    voltage: "22 kV"
  },
  {
    id: "oil-distribution-1600kva-efficiency",
    title: "1600 kVA Tier 2 Efficiency Test Report",
    type: "efficiency-report",
    productIds: ["oil-immersed-distribution-transformer"],
    issuer: "TÜV Rheinland",
    reportNo: "CN25NEY4 001",
    testedModel: "S-M-1600/22-Tier2",
    ratedPower: "1600 kVA",
    ratedVoltage: "22 / 0.42 kV",
    standards: [],
    previewImages: preview("oil-distribution-1600kva-efficiency", ["cover", "summary", "parameters", "product-photo"]),
    pdf: pdf("oil-distribution-1600kva-efficiency"),
    featured: true,
    tags: ["EFFICIENCY", "TÜV"],
    voltage: "22 kV"
  },
  {
    id: "oil-distribution-1600kva-ce",
    title: "1600 kVA CE / Ecodesign Verification",
    type: "ce-verification",
    productIds: ["oil-immersed-distribution-transformer"],
    issuer: "TÜV Rheinland",
    reportNo: "CN25NEY4 001",
    testedModel: "S-M-1600/22-Tier2",
    ratedPower: "1600 kVA",
    ratedVoltage: "22 / 0.42 kV",
    standards: [],
    previewImages: preview("oil-distribution-1600kva-ce", ["cover"]),
    pdf: pdf("oil-distribution-1600kva-ce"),
    featured: true,
    tags: ["CE", "ECODESIGN"],
    voltage: "22 kV"
  },
  {
    id: "oil-distribution-630kva-tuv",
    title: "630 kVA 22 kV TÜV Certificate of Conformity",
    type: "certificate",
    productIds: ["oil-immersed-distribution-transformer"],
    issuer: "TÜV Rheinland",
    reportNo: "AK 50683807 0001",
    testedModel: "S-M-630/22-Tier2",
    ratedPower: "630 kVA",
    ratedVoltage: "22 / 0.42 kV",
    standards: [],
    previewImages: preview("oil-distribution-630kva-tuv", ["cover"]),
    pdf: pdf("oil-distribution-630kva-tuv"),
    featured: true,
    tags: ["TÜV", "CERTIFICATE"],
    voltage: "22 kV"
  },
  {
    id: "oil-distribution-630kva-type-test",
    title: "630 kVA 22 kV Complete Type Test Report",
    type: "type-test",
    productIds: ["oil-immersed-distribution-transformer"],
    issuer: "TÜV Rheinland",
    reportNo: "CN25IM0T 001",
    testedModel: "S-M-630/22-Tier2",
    ratedPower: "630 kVA",
    ratedVoltage: "22 / 0.42 kV",
    standards: ["IEC 60076 series"],
    previewImages: preview("oil-distribution-630kva-type-test", ["cover", "summary", "parameters", "product-photo"]),
    pdf: pdf("oil-distribution-630kva-type-test"),
    featured: true,
    tags: ["TYPE TEST", "IEC", "TÜV"],
    voltage: "22 kV"
  },
  {
    id: "oil-distribution-630kva-efficiency",
    title: "630 kVA Tier 2 Efficiency Test Report",
    type: "efficiency-report",
    productIds: ["oil-immersed-distribution-transformer"],
    issuer: "TÜV Rheinland",
    reportNo: "CN2532PX 001",
    testedModel: "S-M-630/22-Tier2",
    ratedPower: "630 kVA",
    ratedVoltage: "22 / 0.42 kV",
    standards: [],
    previewImages: preview("oil-distribution-630kva-efficiency", ["cover", "summary", "parameters", "product-photo"]),
    pdf: pdf("oil-distribution-630kva-efficiency"),
    featured: true,
    tags: ["EFFICIENCY", "TÜV"],
    voltage: "22 kV"
  },
  {
    id: "oil-distribution-630kva-ce",
    title: "630 kVA CE / Ecodesign Verification",
    type: "ce-verification",
    productIds: ["oil-immersed-distribution-transformer"],
    issuer: "TÜV Rheinland",
    reportNo: "CN2532PX 001",
    testedModel: "S-M-630/22-Tier2",
    ratedPower: "630 kVA",
    ratedVoltage: "22 / 0.42 kV",
    standards: [],
    previewImages: preview("oil-distribution-630kva-ce", ["cover"]),
    pdf: pdf("oil-distribution-630kva-ce"),
    featured: true,
    tags: ["CE", "ECODESIGN"],
    voltage: "22 kV"
  },
  {
    id: "power-transformer-50mva-110kv",
    title: "50 MVA 110 kV Power Transformer Test Report",
    type: "test-report",
    productIds: ["high-voltage-power-transformer"],
    issuer: "Suzhou Electrical Apparatus Science Research Institute",
    reportNo: "21M2078-S",
    testedModel: "SZ22-50000/110-NX1",
    ratedPower: "50 MVA",
    ratedVoltage: "110 kV",
    standards: [],
    previewImages: preview("power-transformer-50mva-110kv", ["cover", "summary", "parameters", "product-photo"]),
    pdf: pdf("power-transformer-50mva-110kv"),
    featured: true,
    tags: ["TEST REPORT", "110 kV"],
    voltage: "110 kV"
  },
  {
    id: "power-transformer-150mva-132kv",
    title: "150 MVA 132 kV Power Transformer Test Report",
    type: "test-report",
    productIds: ["high-voltage-power-transformer"],
    issuer: "Suzhou Electrical Apparatus Science Research Institute",
    reportNo: "21M2079-S",
    testedModel: "SFZ-150000/132",
    ratedPower: "150 MVA",
    ratedVoltage: "132 kV",
    standards: [],
    previewImages: preview("power-transformer-150mva-132kv", ["cover", "summary", "parameters", "product-photo"]),
    pdf: pdf("power-transformer-150mva-132kv"),
    featured: true,
    tags: ["TEST REPORT", "132 kV"],
    voltage: "132 kV"
  },
  {
    id: "power-transformer-240mva-220kv-ssz20",
    title: "240 MVA 220 kV SSZ20 Type Test Report",
    type: "type-test",
    productIds: ["high-voltage-power-transformer"],
    issuer: "Suzhou Electrical Apparatus Science Research Institute",
    reportNo: "21M0905-S",
    testedModel: "SSZ20-240000/220",
    ratedPower: "240 MVA",
    ratedVoltage: "220 kV",
    standards: [],
    previewImages: preview("power-transformer-240mva-220kv-ssz20", ["cover", "summary", "parameters", "product-photo"]),
    pdf: pdf("power-transformer-240mva-220kv-ssz20"),
    featured: true,
    tags: ["TYPE TEST", "220 kV"],
    voltage: "220 kV"
  },
  {
    id: "power-transformer-240mva-220kv-ssz22",
    title: "240 MVA 220 kV SSZ22 Test Report",
    type: "test-report",
    productIds: ["high-voltage-power-transformer"],
    issuer: "Suzhou Electrical Apparatus Science Research Institute",
    reportNo: "23M1317-S",
    testedModel: "SSZ22-240000/220-NX1",
    ratedPower: "240 MVA",
    ratedVoltage: "220 kV",
    standards: [],
    previewImages: preview("power-transformer-240mva-220kv-ssz22", ["cover", "summary", "parameters", "product-photo"]),
    pdf: pdf("power-transformer-240mva-220kv-ssz22"),
    featured: true,
    tags: ["TEST REPORT", "220 kV"],
    voltage: "220 kV"
  },
  {
    id: "dry-type-scb18-1000kva-10kv",
    title: "SCB18 1000 kVA 10 kV Type Test Report",
    type: "type-test",
    productIds: ["cast-resin-dry-type-transformer"],
    issuer: "Suzhou Electrical Apparatus Science Research Institute",
    reportNo: "26N0284-S",
    testedModel: "SCB18-1000/10-NX1",
    ratedPower: "1000 kVA",
    ratedVoltage: "10 kV",
    standards: [],
    previewImages: preview("dry-type-scb18-1000kva-10kv", ["cover", "summary", "parameters", "product-photo"]),
    pdf: pdf("dry-type-scb18-1000kva-10kv"),
    featured: true,
    tags: ["TYPE TEST", "DRY TYPE"],
    voltage: "10 kV"
  },
  {
    id: "dry-type-scb18-2500kva-10kv",
    title: "SCB18 2500 kVA 10 kV Type Test Report",
    type: "type-test",
    productIds: ["cast-resin-dry-type-transformer"],
    issuer: "Suzhou Electrical Apparatus Science Research Institute",
    reportNo: "26N0286-S",
    testedModel: "SCB18-2500/10",
    ratedPower: "2500 kVA",
    ratedVoltage: "10 kV",
    standards: [],
    previewImages: preview("dry-type-scb18-2500kva-10kv", ["cover", "summary", "parameters", "product-photo"]),
    pdf: pdf("dry-type-scb18-2500kva-10kv"),
    featured: true,
    tags: ["TYPE TEST", "DRY TYPE"],
    voltage: "10 kV"
  },
  ...[
    ["european-substation-6300kva-35kv", "6300 kVA 35 kV Dry-Type Prefabricated Substation Type Test Report", "23XB0121-S", "YB-40.5/1.14-6300", "6300 kVA"],
    ["european-substation-10000kva-35kv", "10000 kVA 35 kV Dry-Type Prefabricated Substation Type Test Report", "26XB0130-S", "YB-40.5/1.14-10000", "10000 kVA"],
    ["european-substation-12500kva-35kv", "12500 kVA 35 kV Dry-Type Prefabricated Substation Type Test Report", "26XB0131-S", "YB-40.5/1.14-12500", "12500 kVA"]
  ].map(([id, title, reportNo, testedModel, ratedPower]) => ({
    id, title, type: "type-test",
    productIds: ["dry-type-prefabricated-substation"],
    issuer: "Suzhou Electrical Apparatus Science Research Institute",
    reportNo, testedModel, ratedPower, ratedVoltage: "35 kV", standards: [],
    previewImages: preview(id, ["cover", "summary", "parameters", "product-photo"]),
    pdf: pdf(id), featured: true, tags: ["TYPE TEST", "35 kV"], voltage: "35 kV"
  })),
  ...[
    ["china-substation-10000kva-35kv", "10000 kVA 35 kV GY Series Prefabricated Substation Type Test Report", "26XB0129-S", "YB-40.5-10000", "10000 kVA"],
    ["china-substation-12500kva-35kv", "12500 kVA 35 kV GY Series Prefabricated Substation Type Test Report", "Report on supplied PDF", "YB-40.5/1.14-12500 (GY)", "12500 kVA"]
  ].map(([id, title, reportNo, testedModel, ratedPower]) => ({
    id, title, type: "type-test",
    productIds: ["oil-immersed-prefabricated-substation"],
    issuer: "Suzhou Electrical Apparatus Science Research Institute",
    reportNo, testedModel, ratedPower, ratedVoltage: "35 kV", standards: [],
    previewImages: preview(id, ["cover", "summary", "parameters", "product-photo"]),
    pdf: pdf(id), featured: true, tags: ["TYPE TEST", "35 kV"], voltage: "35 kV"
  })),
  {
    id: "american-combined-transformer-pending",
    title: "ZGS22-4000/35/0.8 Combined Transformer Certificate",
    type: "certificate",
    productIds: ["american-type-combined-transformer"],
    issuer: null,
    reportNo: null,
    testedModel: "ZGS22-4000/35/0.8",
    ratedPower: "4000 kVA",
    ratedVoltage: "35 / 0.8 kV",
    standards: [],
    previewImages: [],
    pdf: null,
    featured: false,
    tags: ["ASSET PENDING"],
    voltage: "35 kV",
    status: "pending-asset"
  }
];

export const drawings = [
  ...["6300", "10000", "12500"].map((capacity) => ({
    id: `european-substation-${capacity}kva-35kv-outline`,
    title: `${capacity} kVA Prefabricated Substation Outline Drawing`,
    type: "Outline Drawing",
    productIds: ["dry-type-prefabricated-substation"],
    image: `drawings/european-substation-${capacity}kva-35kv-outline.webp`,
    note: "REFERENCE DRAWING - Final drawing subject to project design."
  })),
  ...["10000", "12500"].map((capacity) => ({
    id: `china-substation-${capacity}kva-35kv-outline`,
    title: `${capacity} kVA GY Series Substation Outline Drawing`,
    type: "Outline Drawing",
    productIds: ["oil-immersed-prefabricated-substation"],
    image: `drawings/china-substation-${capacity}kva-35kv-outline.webp`,
    note: "REFERENCE DRAWING - Final drawing subject to project design."
  }))
];

export const documentById = new Map(documents.map((document) => [document.id, document]));
export const drawingById = new Map(drawings.map((drawing) => [drawing.id, drawing]));
