export function rfqPage() {
  return String.raw`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Guided Transformer RFQ Selector | Tianyu Electric</title>
  <meta name="description" content="Guided transformer RFQ selector for staged engineering review.">
  <link rel="stylesheet" href="assets/css/styles.css">
  <style>
    .rfq-hero{padding:clamp(54px,7vw,86px) clamp(18px,5vw,70px);background:linear-gradient(135deg,#06243f,#063b66)}
    .rfq-hero h1{max-width:980px;color:white;font-size:clamp(38px,5vw,66px)}.rfq-hero p{max-width:780px;color:rgba(255,255,255,.86);font-size:18px}
    .rfq-shell{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:24px;align-items:start}.rfq-form{display:grid;gap:22px}
    .rfq-step{background:white;border:1px solid var(--line);border-radius:14px;padding:clamp(22px,3vw,32px);box-shadow:0 10px 28px rgba(8,35,58,.06)}.rfq-step h2{font-size:clamp(25px,3vw,36px)}
    .rfq-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.full{grid-column:1/-1}.option-row{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}
    .option-card{display:block;border:1px solid var(--line);border-radius:12px;padding:16px;background:#fbfcfd;cursor:pointer}.option-card input,.checkbox-row input{width:auto;margin-right:8px}.option-card strong{color:var(--blue-dark)}
    .checkbox-row{display:flex;flex-wrap:wrap;gap:10px}.checkbox-row label{display:inline-flex;align-items:center;border:1px solid var(--line);border-radius:999px;padding:9px 12px;background:#fbfcfd}
    .advanced{margin-top:12px;border:1px solid var(--line);border-radius:12px;background:#fbfcfd}.advanced summary{padding:15px 18px;cursor:pointer;font-weight:800;color:var(--blue-dark)}.advanced .rfq-grid{padding:0 18px 18px}
    .summary-card{position:sticky;top:96px;background:var(--blue-dark);color:white;border-radius:14px;padding:22px;box-shadow:var(--shadow)}.summary-card h2,.summary-card p,.summary-card dt,.summary-card dd{color:white}.summary-card dt{color:#8ef0e2;font-weight:800;margin-top:12px}.summary-card dd{margin:2px 0 0;color:rgba(255,255,255,.86)}
    [hidden]{display:none!important}@media(max-width:980px){.rfq-shell{grid-template-columns:1fr}.summary-card{position:static}}@media(max-width:680px){.rfq-grid,.option-row{grid-template-columns:1fr}}
  </style>
</head>
<body>
  <header class="site-header">
    <a class="brand" href="index.html"><span class="brand-mark">TY</span><span><strong>Tianyu Electric</strong><small>Power Primary Equipment</small></span></a>
    <button class="menu-toggle" aria-label="Open navigation" data-menu-toggle>Menu</button>
    <nav class="main-nav" data-nav><a href="index.html">Home</a><a href="products.html">Products</a><a href="applications.html">Applications & Projects</a><a href="news.html">News</a><a href="about.html">Company</a><a class="active" href="rfq.html">RFQ</a><a href="contact.html">Contact</a></nav>
    <div class="header-actions"><span class="language">EN</span><a class="btn btn-primary" href="contact.html">Contact Us</a></div>
  </header>
  <main>
    <section class="rfq-hero"><p class="eyebrow">Guided RFQ Selector</p><h1>Short selection first. Detailed technical table only when the buyer is ready.</h1><p>This page turns transformer inquiry into four staged steps: basic classification, structure details, basic electrical parameters, then optional advanced engineering details.</p></section>
    <section class="section rfq-shell">
      <form class="rfq-form" data-rfq-form>
        <section class="rfq-step"><p class="eyebrow">Step 1</p><h2>Basic Selection / 基础选择</h2><p>These fields answer: what body it has, whether it steps voltage, where it is used, and what role it plays.</p>
          <h3>Product Structure / 本体结构</h3><div class="option-row">
            <label class="option-card"><input type="radio" name="productStructure" value="Liquid-Immersed / Liquid-Filled Transformer" data-structure="liquid" checked><strong>Liquid-Immersed / Liquid-Filled</strong><br><small>Oil or liquid insulation, tank and oil cooling.</small></label>
            <label class="option-card"><input type="radio" name="productStructure" value="Dry-Type Transformer" data-structure="dry"><strong>Dry-Type Transformer</strong><br><small>Cast resin, VPI, enclosure and air cooling.</small></label>
            <label class="option-card"><input type="radio" name="productStructure" value="Prefabricated Transformer Substation" data-structure="future"><strong>Prefabricated Substation</strong><br><small>Future module, not expanded in V1.0.</small></label>
            <label class="option-card"><input type="radio" name="productStructure" value="Transformer Accessories & Components" data-structure="future"><strong>Accessories & Components</strong><br><small>Future module, not expanded in V1.0.</small></label>
          </div>
          <div class="rfq-grid" style="margin-top:18px">
            <label>Voltage Transformation / 电压变换方向<select name="voltageTransformation"><option>Step-Up / 升压</option><option>Step-Down / 降压</option><option>Isolation / Same Voltage / 隔离或等电压</option><option>Multiple Output / Multi-Winding / 多输出或多绕组</option><option>Not Sure / 不确定</option></select></label>
            <label>Application Scenario / 使用场景<select name="applicationScenario"><option>Utility Grid / 公用电网</option><option>Substation / 变电站</option><option>Solar Power Plant / 光伏电站</option><option>Wind Farm / 风电场</option><option>BESS / 储能系统</option><option>Data Center / 数据中心</option><option>Industrial Plant / 工业工厂</option><option>Commercial Building / 商业建筑</option><option>Mining / 矿山</option><option>Marine / Offshore / 船舶或海工</option><option>Railway / Traction / 铁路或牵引</option><option>Testing Laboratory / 试验站或实验室</option><option>Other / 其他</option></select></label>
            <label>Engineering Role / 工程角色<select name="engineeringRole"><option>Distribution Network Transformer / 配电网络变压器</option><option>Substation Main Transformer / 变电站主变压器</option><option>Generation Step-Up Transformer / 发电升压变压器</option><option>Auxiliary / Service Transformer / 站用电或厂用电</option><option>Industrial Process Transformer / 工业工艺负载</option><option>Building Service Transformer / 建筑供配电</option><option>Testing Transformer / 试验变压器</option><option>Replacement / Retrofit Transformer / 替换或改造</option><option>Other / Not Sure / 其他或不确定</option></select></label>
            <label>Project Stage / 项目阶段<select name="projectStage"><option>Early Selection / 初步选型</option><option>Formal RFQ / 正式询价</option><option>Tender / 招标</option><option>Replacement / 替换项目</option><option>Not Sure / 不确定</option></select></label>
          </div>
          <h3 style="margin-top:22px">Special Requirement / 特殊要求</h3><div class="checkbox-row"><label><input type="checkbox" name="specialRequirement" value="Not Sure / 不确定" checked>Not Sure</label><label><input type="checkbox" name="specialRequirement" value="Isolation">Isolation</label><label><input type="checkbox" name="specialRequirement" value="K-Rated / Nonlinear Load">K-Rated</label><label><input type="checkbox" name="specialRequirement" value="Rectifier / Converter">Rectifier</label><label><input type="checkbox" name="specialRequirement" value="Grounding / Earthing">Grounding</label><label><input type="checkbox" name="specialRequirement" value="Low Noise">Low Noise</label><label><input type="checkbox" name="specialRequirement" value="Low Loss">Low Loss</label><label><input type="checkbox" name="specialRequirement" value="Fire Resistant">Fire Resistant</label></div>
        </section>
        <section class="rfq-step"><p class="eyebrow">Step 2</p><h2>Structure Details / 结构细节</h2>
          <div data-panel="liquid"><div class="rfq-grid"><label>Insulating Liquid / 绝缘液体<select name="insulatingLiquid"><option>Mineral Oil / 矿物油</option><option>Natural Ester / 天然酯</option><option>Synthetic Ester / 合成酯</option><option>Silicone Fluid / 硅油</option><option>Fire-Resistant Liquid / 难燃液体</option><option>Not Sure / 不确定</option></select></label><label>Tank Structure / 油箱结构<select name="tankStructure"><option>Hermetically Sealed / 全密封</option><option>Conservator Type / 储油柜式</option><option>Corrugated Tank / 波纹油箱</option><option>Radiator Type / 散热器式</option><option>Gas Cushion Type / 气垫式</option><option>Not Sure / 不确定</option></select></label><label>Cooling Method / 冷却方式<select name="liquidCooling"><option>ONAN / 油浸自冷</option><option>ONAF / 油浸风冷</option><option>OFAF / 强迫油循环风冷</option><option>ODAF / 强迫导向油循环风冷</option><option>OFWF / ODWF / 油水冷却</option><option>Not Sure / 不确定</option></select></label></div></div>
          <div data-panel="dry" hidden><div class="rfq-grid"><label>Insulation System / 绝缘体系<select name="dryInsulation"><option>Cast Resin / 环氧浇注</option><option>Resin Encapsulated / 树脂包封</option><option>VPI / 真空压力浸渍</option><option>VPE / 真空压力包封</option><option>Open Wound / 开放绕组</option><option>Not Sure / 不确定</option></select></label><label>Core Material / 铁芯材料<select name="coreMaterial"><option>Silicon Steel / 硅钢片</option><option>Amorphous Alloy / 非晶合金</option><option>Not Sure / 不确定</option></select></label><label>Enclosure Type / 外壳形式<select name="enclosureType"><option>Open Type / 开放式</option><option>Ventilated Enclosure / 通风外壳</option><option>Non-Ventilated Enclosure / 非通风外壳</option><option>Sealed Enclosure / 密封外壳</option><option>Indoor Enclosure / 户内外壳</option><option>Outdoor Enclosure / 户外外壳</option><option>IP Customized / IP等级定制</option><option>Not Sure / 不确定</option></select></label><label>Cooling Method / 冷却方式<select name="dryCooling"><option>AN / 空气自冷</option><option>AF / 强迫风冷</option><option>AN / AF / 自冷加风冷增容</option><option>Not Sure / 不确定</option></select></label></div></div>
          <div data-panel="future" hidden><p class="source-note">This product body is reserved as a future module. The buyer can still submit basic notes and upload a specification.</p></div>
        </section>
        <section class="rfq-step"><p class="eyebrow">Step 3</p><h2>Technical Details / 技术参数</h2><div class="rfq-grid"><label>Rated Capacity / 额定容量<input name="ratedCapacity" placeholder="e.g. 1000 kVA"></label><label>Primary Voltage / 一次电压<input name="primaryVoltage" placeholder="e.g. 13.8 kV"></label><label>Secondary Voltage / 二次电压<input name="secondaryVoltage" placeholder="e.g. 480 V"></label><label>Frequency / 频率<select name="frequency"><option>50 Hz</option><option>60 Hz</option><option>Not Sure / 不确定</option></select></label><label>Phase / 相数<select name="phase"><option>Three Phase / 三相</option><option>Single Phase / 单相</option><option>Not Sure / 不确定</option></select></label><label>Quantity / 数量<input name="quantity" placeholder="e.g. 2 units"></label><label>Installation / 安装位置<select name="installation"><option>Indoor / 户内</option><option>Outdoor / 户外</option><option>Containerized / 集装箱</option><option>Not Sure / 不确定</option></select></label><label>Destination Country / 使用国家<input name="country" placeholder="e.g. United States"></label><label class="full">Upload Specification / 上传规格书<input name="file" type="file"></label></div>
          <details class="advanced"><summary>Advanced Technical Details / 高级技术参数，可选填写</summary><div class="rfq-grid"><label>Connection Group / 联结组别<input name="connectionGroup" data-advanced placeholder="e.g. Dyn11"></label><label>Impedance Voltage / 阻抗电压<input name="impedance" data-advanced placeholder="e.g. 6%"></label><label>Tap Changer / 调压方式<select name="tapChanger" data-advanced><option value="">Not specified / 未指定</option><option>No Tap Changer / 无调压</option><option>OCTC / 无励磁调压</option><option>OLTC / 有载调压</option><option>Not Sure / 不确定</option></select></label><label>Standard / 执行标准<select name="standard" data-advanced><option value="">Not specified / 未指定</option><option>IEC</option><option>IEEE / ANSI</option><option>DOE Efficiency</option><option>CSA</option><option>EN / EcoDesign</option><option>Other / Not Sure</option></select></label><label class="full">Other Requirements / 其他要求<textarea name="otherRequirements" rows="3" data-advanced></textarea></label></div></details>
        </section>
        <section class="rfq-step"><p class="eyebrow">Step 4</p><h2>Review & Submit / 摘要确认并提交</h2><p class="source-note">Prototype only. Connect this form to email, CRM or backend before launch.</p><button class="btn btn-primary" type="submit">Submit RFQ for Engineering Review</button></section>
      </form>
      <aside class="summary-card" data-summary><p class="eyebrow">Live Summary</p><h2>Inquiry Summary</h2><p>Selection will appear here.</p></aside>
    </section>
  </main>
  <footer class="footer"><div class="footer-grid"><div><h2>Tianyu Electric</h2><p>Transformer-focused B2B website first version.</p></div><div><h3>Products</h3><a href="products.html">Transformer Products</a><a href="rfq.html">Guided RFQ Selector</a></div><div><h3>Applications</h3><a href="applications.html">Applications & Projects</a></div><div><h3>Company</h3><a href="about.html">About Us</a><a href="contact.html">Contact</a></div></div><div class="footer-bottom"><span>© 2026 Tianyu Electric</span><a href="privacy.html">Privacy Policy</a></div></footer>
  <script>
    var form=document.querySelector('[data-rfq-form]'),summary=document.querySelector('[data-summary]'),panels=[].slice.call(document.querySelectorAll('[data-panel]'));
    function value(name){return form.elements[name]&&form.elements[name].value?form.elements[name].value:'Not specified'}
    function radio(name){var item=form.querySelector('input[name="'+name+'"]:checked');return item?item.value:'Not specified'}
    function checks(name){return [].slice.call(form.querySelectorAll('input[name="'+name+'"]:checked')).map(function(x){return x.value}).join(', ')||'Not specified'}
    function refresh(){var selected=(form.querySelector('input[name="productStructure"]:checked')||{}).dataset?.structure||'liquid';panels.forEach(function(p){p.hidden=p.dataset.panel!==selected});var structure=selected==='liquid'?[value('insulatingLiquid'),value('tankStructure'),value('liquidCooling')].join(' | '):selected==='dry'?[value('dryInsulation'),value('coreMaterial'),value('enclosureType'),value('dryCooling')].join(' | '):'Future module, engineering review required';var adv=[].slice.call(form.querySelectorAll('[data-advanced]')),filled=adv.filter(function(x){return x.value}).length;var rows=[['Product Structure',radio('productStructure')],['Voltage Direction',value('voltageTransformation')],['Application',value('applicationScenario')],['Engineering Role',value('engineeringRole')],['Special Requirements',checks('specialRequirement')],['Structure Details',structure],['Basic Parameters',[value('ratedCapacity'),value('primaryVoltage'),value('secondaryVoltage'),value('frequency'),value('phase')].join(' | ')],['Installation & Country',[value('installation'),value('country')].join(' | ')],['Advanced Details',filled+' optional fields filled, '+(adv.length-filled)+' to be confirmed']];summary.innerHTML='<p class="eyebrow">Live Summary</p><h2>Inquiry Summary</h2><dl>'+rows.map(function(r){return '<dt>'+r[0]+'</dt><dd>'+(r[1]||'Not specified')+'</dd>'}).join('')+'</dl>'}
    form.addEventListener('input',refresh);form.addEventListener('change',refresh);form.addEventListener('submit',function(e){e.preventDefault();alert('RFQ captured for prototype review. Connect this form to email or CRM before launch.')});refresh();
  </script>
</body>
</html>`;
}
