export function rfqPage() {
  return String.raw`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Guided Transformer RFQ Selector | Tianyu Electric</title>
  <meta name="description" content="Guided transformer RFQ selector with staged classification and complete optional technical table for engineering review.">
  <link rel="stylesheet" href="assets/css/styles.css">
  <style>
    .rfq-hero{padding:clamp(54px,7vw,86px) clamp(18px,5vw,70px);background:linear-gradient(135deg,#06243f,#063b66)}
    .rfq-hero h1{max-width:980px;color:white;font-size:clamp(38px,5vw,66px)}.rfq-hero p{max-width:820px;color:rgba(255,255,255,.86);font-size:18px}
    .rfq-shell{display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:24px;align-items:start}.rfq-form{display:grid;gap:22px}
    .rfq-step{background:white;border:1px solid var(--line);border-radius:14px;padding:clamp(22px,3vw,32px);box-shadow:0 10px 28px rgba(8,35,58,.06)}.rfq-step h2{font-size:clamp(25px,3vw,36px)}
    .rfq-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.full{grid-column:1/-1}.option-row{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}
    .option-card{display:block;border:1px solid var(--line);border-radius:12px;padding:16px;background:#fbfcfd;cursor:pointer}.option-card input,.checkbox-row input{width:auto;margin-right:8px}.option-card strong{color:var(--blue-dark)}
    .checkbox-row{display:flex;flex-wrap:wrap;gap:10px}.checkbox-row label{display:inline-flex;align-items:center;border:1px solid var(--line);border-radius:999px;padding:9px 12px;background:#fbfcfd}
    .technical-table{margin-top:16px;border:1px solid var(--line);border-radius:14px;overflow:hidden;background:white}.technical-group{border-top:1px solid var(--line);padding:18px}.technical-group:first-child{border-top:0}.technical-group h3{margin-bottom:14px}.field-note{display:block;color:var(--muted);font-weight:400;font-size:12px}.optional-badge{display:inline-flex;margin-left:8px;padding:3px 8px;border-radius:999px;background:#e7f4f2;color:#0a6e6e;font-size:12px;font-weight:800}
    .advanced{margin-top:12px;border:1px solid var(--line);border-radius:12px;background:#fbfcfd}.advanced summary{padding:15px 18px;cursor:pointer;font-weight:800;color:var(--blue-dark)}
    .summary-card{position:sticky;top:96px;background:var(--blue-dark);color:white;border-radius:14px;padding:22px;box-shadow:var(--shadow)}.summary-card h2,.summary-card p,.summary-card dt,.summary-card dd{color:white}.summary-card dt{color:#8ef0e2;font-weight:800;margin-top:12px}.summary-card dd{margin:2px 0 0;color:rgba(255,255,255,.86)}
    .helper-panel{padding:14px 16px;background:#edf5f5;border-left:4px solid var(--teal);color:#385767;font-weight:700}.muted-small{font-size:13px;color:var(--muted)}
    [hidden]{display:none!important}@media(max-width:980px){.rfq-shell{grid-template-columns:1fr}.summary-card{position:static}}@media(max-width:680px){.rfq-grid,.option-row{grid-template-columns:1fr}}
  </style>
</head>
<body>
  <header class="site-header">
    <a class="brand" href="index.html"><span class="brand-mark">TY</span><span><strong>Tianyu Electric</strong><small>Power Primary Equipment</small></span></a>
    <button class="menu-toggle" aria-label="Open navigation" data-menu-toggle>Menu</button>
    <nav class="main-nav" data-nav><a href="index.html">Home</a><a href="products.html">Products</a><a href="applications.html">Applications & Projects</a><a href="news.html">News</a><a href="about.html">Company</a><a class="active" href="rfq.html">RFQ</a><a href="contact.html">Contact</a></nav>
    <div class="header-actions"><span class="language">EN</span><a class="btn btn-primary" href="contact.html">Contact Us</a></div>
  </header>
  <main>
    <section class="rfq-hero"><p class="eyebrow">Guided RFQ Selector</p><h1>Short selection first. Complete technical table only after the buyer enters RFQ mode.</h1><p>This page turns transformer inquiry into four staged steps: basic classification, structure details, basic electrical parameters, and a complete optional technical table for engineering review.</p></section>
    <section class="section rfq-shell">
      <form class="rfq-form" data-rfq-form>
        <section class="rfq-step"><p class="eyebrow">Step 1</p><h2>Basic Selection / 基础选择</h2><p>These fields answer: what body it has, whether it steps voltage, where it is used, and what role it plays.</p>
          <h3>Product Structure / 本体结构</h3><div class="option-row">
            <label class="option-card"><input type="radio" name="productStructure" value="Liquid-Immersed / Liquid-Filled Transformer" data-structure="liquid" checked><strong>Liquid-Immersed / Liquid-Filled</strong><br><small>Oil or liquid insulation, tank and oil cooling.</small></label>
            <label class="option-card"><input type="radio" name="productStructure" value="Dry-Type Transformer" data-structure="dry"><strong>Dry-Type Transformer</strong><br><small>Cast resin, VPI, enclosure and air cooling.</small></label>
            <label class="option-card"><input type="radio" name="productStructure" value="Prefabricated Transformer Substation" data-structure="future"><strong>Prefabricated Substation</strong><br><small>Future module, not expanded in V1.0.</small></label>
            <label class="option-card"><input type="radio" name="productStructure" value="Transformer Accessories & Components" data-structure="future"><strong>Accessories & Components</strong><br><small>Future module, not expanded in V1.0.</small></label>
          </div>
          <div class="rfq-grid" style="margin-top:18px">
            <label>Voltage Transformation / 电压变换方向<select name="voltageTransformation"><option>Step-Up / 升压</option><option>Step-Down / 降压</option><option>Isolation / Same Voltage / 隔离或等电压</option><option>Multiple Output / Multi-Winding / 多输出或多绕组</option><option>Not Sure / 不确定</option></select></label>
            <label>Application Scenario / 使用场景<select name="applicationScenario"><option>Utility Grid / 公用电网</option><option>Substation / 变电站</option><option>Solar Power Plant / 光伏电站</option><option>Wind Farm / 风电场</option><option>BESS / 储能系统</option><option>Data Center / 数据中心</option><option>Industrial Plant / 工业工厂</option><option>Commercial Building / 商业建筑</option><option>Mining / 矿山</option><option>Marine / Offshore / 船舶或海工</option><option>Railway / Traction / 铁路或牵引</option><option>Testing Laboratory / 试验站或实验室</option><option>Other / 其他</option></select></label>
            <label>Engineering Role / 工程角色<select name="engineeringRole"><option>Distribution Network Transformer / 配电网络变压器</option><option>Substation Main Transformer / 变电站主变压器</option><option>Generation Step-Up Transformer / 发电升压变压器</option><option>Auxiliary / Service Transformer / 站用电或厂用电</option><option>Industrial Process Transformer / 工业工艺负载</option><option>Building Service Transformer / 建筑供配电</option><option>Testing Transformer / 试验变压器</option><option>Replacement / Retrofit Transformer / 替换或改造</option><option>Other / Not Sure / 其他或不确定</option></select></label>
            <label>Project Stage / 项目阶段<select name="projectStage"><option>Early Selection / 初步选型</option><option>Formal RFQ / 正式询价</option><option>Tender / 招标</option><option>Replacement / 替换项目</option><option>Not Sure / 不确定</option></select></label>
          </div>
          <h3 style="margin-top:22px">Special Requirement / 特殊要求</h3><div class="checkbox-row"><label><input type="checkbox" name="specialRequirement" value="Not Sure / 不确定" checked>Not Sure</label><label><input type="checkbox" name="specialRequirement" value="Isolation">Isolation</label><label><input type="checkbox" name="specialRequirement" value="Shielded Isolation">Shielded Isolation</label><label><input type="checkbox" name="specialRequirement" value="K-Rated / Nonlinear Load">K-Rated</label><label><input type="checkbox" name="specialRequirement" value="Harmonic Mitigation">Harmonic Mitigation</label><label><input type="checkbox" name="specialRequirement" value="Rectifier / Converter">Rectifier</label><label><input type="checkbox" name="specialRequirement" value="Grounding / Earthing">Grounding</label><label><input type="checkbox" name="specialRequirement" value="Phase-Shifting">Phase-Shifting</label><label><input type="checkbox" name="specialRequirement" value="Low Noise">Low Noise</label><label><input type="checkbox" name="specialRequirement" value="Low Loss">Low Loss</label><label><input type="checkbox" name="specialRequirement" value="Fire Resistant">Fire Resistant</label></div>
        </section>
        <section class="rfq-step"><p class="eyebrow">Step 2</p><h2>Structure Details / 结构细节</h2>
          <div data-panel="liquid"><div class="rfq-grid"><label>Insulating Liquid / 绝缘液体<select name="insulatingLiquid"><option>Mineral Oil / 矿物油</option><option>Natural Ester / 天然酯</option><option>Synthetic Ester / 合成酯</option><option>Silicone Fluid / 硅油</option><option>Fire-Resistant Liquid / 难燃液体</option><option>Other / 其他</option><option>Not Sure / 不确定</option></select></label><label>Tank Structure / 油箱结构<select name="tankStructure"><option>Hermetically Sealed / 全密封</option><option>Conservator Type / 储油柜式</option><option>Corrugated Tank / 波纹油箱</option><option>Radiator Type / 散热器式</option><option>Gas Cushion Type / 气垫式</option><option>Other / 其他</option><option>Not Sure / 不确定</option></select></label><label>Cooling Method / 冷却方式<select name="liquidCooling"><option>ONAN / 油浸自冷</option><option>ONAF / 油浸风冷</option><option>OFAF / 强迫油循环风冷</option><option>ODAF / 强迫导向油循环风冷</option><option>OFWF / ODWF / 油水冷却</option><option>Other / 其他</option><option>Not Sure / 不确定</option></select></label></div></div>
          <div data-panel="dry" hidden><div class="rfq-grid"><label>Insulation System / 绝缘体系<select name="dryInsulation"><option>Cast Resin / 环氧浇注</option><option>Resin Encapsulated / 树脂包封</option><option>VPI / 真空压力浸渍</option><option>VPE / 真空压力包封</option><option>Open Wound / 开放绕组</option><option>Other / 其他</option><option>Not Sure / 不确定</option></select></label><label>Core Material / 铁芯材料<select name="coreMaterial"><option>Silicon Steel / 硅钢片</option><option>Amorphous Alloy / 非晶合金</option><option>Other / 其他</option><option>Not Sure / 不确定</option></select></label><label>Enclosure Type / 外壳形式<select name="enclosureType"><option>Open Type / 开放式</option><option>Ventilated Enclosure / 通风外壳</option><option>Non-Ventilated Enclosure / 非通风外壳</option><option>Sealed Enclosure / 密封外壳</option><option>Indoor Enclosure / 户内外壳</option><option>Outdoor Enclosure / 户外外壳</option><option>IP Customized / IP等级定制</option><option>Other / 其他</option><option>Not Sure / 不确定</option></select></label><label>Cooling Method / 冷却方式<select name="dryCooling"><option>AN / 空气自冷</option><option>AF / 强迫风冷</option><option>AN / AF / 自冷加风冷增容</option><option>Other / 其他</option><option>Not Sure / 不确定</option></select></label></div></div>
          <div data-panel="future" hidden><p class="source-note">This product body is reserved as a future module. The buyer can still submit basic notes and upload a specification.</p></div>
        </section>
        <section class="rfq-step"><p class="eyebrow">Step 3</p><h2>Technical Details / 技术参数</h2><div class="helper-panel">Please provide the information already available. The advanced table is optional and can be left as “Not Sure” or blank for engineering review.</div>
          <div class="technical-table">
            <div class="technical-group"><h3>Basic Required Information / 基础必填信息</h3><div class="rfq-grid"><label>Rated Capacity / 额定容量<input name="ratedCapacity" placeholder="e.g. 1000 kVA / 10 MVA"></label><label>Primary Voltage / 一次电压<input name="primaryVoltage" placeholder="e.g. 13.8 kV"></label><label>Secondary Voltage / 二次电压<input name="secondaryVoltage" placeholder="e.g. 480 V"></label><label>Frequency / 频率<select name="frequency"><option>50 Hz</option><option>60 Hz</option><option>Not Sure / 不确定</option></select></label><label>Phase / 相数<select name="phase"><option>Three Phase / 三相</option><option>Single Phase / 单相</option><option>Not Sure / 不确定</option></select></label><label>Quantity / 数量<input name="quantity" placeholder="e.g. 2 units"></label><label>Installation / 安装位置<select name="installation"><option>Indoor / 户内</option><option>Outdoor / 户外</option><option>Containerized / 集装箱</option><option>Not Sure / 不确定</option></select></label><label>Destination Country / 使用国家<input name="country" placeholder="e.g. United States"></label><label class="full">Upload Specification / 上传规格书<input name="file" type="file"><span class="field-note">Specification, tender document, BOQ, drawing, or existing transformer nameplate photo.</span></label></div></div>
            <details class="advanced" open><summary>Complete Technical Table / 完整技术表 <span class="optional-badge">Optional</span></summary>
              <div class="technical-group"><h3>1. Electrical Rating & System / 电气额定与系统</h3><div class="rfq-grid"><label>Rated Power / 额定容量<input name="ratedPower" data-advanced placeholder="e.g. 2500 kVA"></label><label>HV Voltage / 高压侧电压<input name="hvVoltage" data-advanced placeholder="e.g. 35 kV"></label><label>LV Voltage / 低压侧电压<input name="lvVoltage" data-advanced placeholder="e.g. 0.4 kV"></label><label>MV / Tertiary Voltage / 中压或第三绕组<input name="tertiaryVoltage" data-advanced placeholder="If applicable"></label><label>Rated Frequency / 额定频率<select name="ratedFrequency" data-advanced><option value="">Not specified</option><option>50 Hz</option><option>60 Hz</option><option>Other / Not Sure</option></select></label><label>Phase / 相数<select name="ratedPhase" data-advanced><option value="">Not specified</option><option>Three Phase</option><option>Single Phase</option><option>Other / Not Sure</option></select></label><label>Connection Group / 联结组别<input name="connectionGroup" data-advanced placeholder="e.g. Dyn11, YNd11"></label><label>Neutral Requirement / 中性点要求<input name="neutralRequirement" data-advanced placeholder="e.g. LV neutral brought out"></label><label>Impedance Voltage / 阻抗电压<input name="impedance" data-advanced placeholder="e.g. 6% / 8% / standard"></label><label>Short-Circuit Level / 短路水平<input name="shortCircuitLevel" data-advanced placeholder="e.g. 25 kA, 31.5 kA"></label></div></div>
              <div class="technical-group"><h3>2. Tapping & Voltage Regulation / 分接与调压</h3><div class="rfq-grid"><label>Tap Range / 分接范围<input name="tapRange" data-advanced placeholder="e.g. ±2 x 2.5%"></label><label>Tap Changer / 调压方式<select name="tapChanger" data-advanced><option value="">Not specified</option><option>No Tap Changer / 无调压</option><option>OCTC / Off-Circuit Tap Changer / 无励磁调压</option><option>OLTC / On-Load Tap Changer / 有载调压</option><option>Not Sure / 不确定</option></select></label><label>Tap Side / 分接位置<select name="tapSide" data-advanced><option value="">Not specified</option><option>HV Side</option><option>LV Side</option><option>Other / Not Sure</option></select></label><label>Voltage Regulation Requirement / 稳压要求<input name="voltageRegulationRequirement" data-advanced placeholder="If applicable"></label></div></div>
              <div class="technical-group"><h3>3. Insulation, Thermal & Environment / 绝缘、温升与环境</h3><div class="rfq-grid"><label>Insulation Level / 绝缘水平<input name="insulationLevel" data-advanced placeholder="e.g. LI/AC values"></label><label>Temperature Rise / 温升<input name="temperatureRise" data-advanced placeholder="e.g. 65K oil / 80K winding"></label><label>Insulation Class / 绝缘等级<select name="insulationClass" data-advanced><option value="">Not specified</option><option>Class A</option><option>Class F</option><option>Class H</option><option>Other / Not Sure</option></select></label><label>Ambient Temperature / 环境温度<input name="ambientTemperature" data-advanced placeholder="e.g. -25°C to +40°C"></label><label>Altitude / 海拔<input name="altitude" data-advanced placeholder="e.g. ≤1000 m"></label><label>Humidity / Corrosion / Pollution / 湿度腐蚀污染<input name="siteEnvironment" data-advanced placeholder="Indoor clean / coastal / mining / desert"></label></div></div>
              <div class="technical-group"><h3>4. Materials & Construction / 材料与结构</h3><div class="rfq-grid"><label>Winding Material / 绕组材料<select name="windingMaterial" data-advanced><option value="">Not specified</option><option>Copper</option><option>Aluminum</option><option>Manufacturer Standard</option><option>Not Sure</option></select></label><label>Core Material / 铁芯材料<select name="advancedCoreMaterial" data-advanced><option value="">Not specified</option><option>Silicon Steel</option><option>Amorphous Alloy</option><option>Manufacturer Standard</option><option>Not Sure</option></select></label><label>Enclosure / Tank Protection / 外壳或油箱防护<input name="tankOrEnclosureProtection" data-advanced placeholder="e.g. IP23, IP54, galvanized"></label><label>Painting / Surface Treatment / 涂装<input name="painting" data-advanced placeholder="e.g. RAL color, C5 corrosion class"></label><label>Dimensions Limit / 尺寸限制<input name="dimensionLimit" data-advanced placeholder="If replacement or site limited"></label><label>Weight Limit / 重量限制<input name="weightLimit" data-advanced placeholder="If transport or foundation limited"></label></div></div>
              <div class="technical-group"><h3>5. Loss, Noise & Special Performance / 损耗、噪音与特殊性能</h3><div class="rfq-grid"><label>Efficiency / Loss Requirement / 能效或损耗要求<input name="lossRequirement" data-advanced placeholder="e.g. DOE, EcoDesign, low-loss design"></label><label>Noise Level / 噪音水平<input name="noiseLevel" data-advanced placeholder="e.g. ≤55 dB"></label><label>Harmonic / K-Factor / 谐波或K系数<input name="harmonicKFactor" data-advanced placeholder="e.g. K-13, K-20, nonlinear load"></label><label>Shield / Electrostatic Screen / 屏蔽要求<input name="shieldRequirement" data-advanced placeholder="If isolation or data center"></label><label>Rectifier / Inverter Duty / 整流或逆变工况<input name="converterDuty" data-advanced placeholder="Pulse number, inverter type, load profile"></label><label>Overload Requirement / 过载要求<input name="overloadRequirement" data-advanced placeholder="If required"></label></div></div>
              <div class="technical-group"><h3>6. Standards, Tests & Documentation / 标准、试验与文件</h3><div class="rfq-grid"><label>Applicable Standard / 执行标准<select name="standard" data-advanced><option value="">Not specified</option><option>IEC</option><option>IEEE / ANSI</option><option>DOE Efficiency</option><option>CSA</option><option>UL</option><option>EN / EcoDesign</option><option>Other / Not Sure</option></select></label><label>Certification Requirement / 认证要求<input name="certificationRequirement" data-advanced placeholder="e.g. UL, CSA, CE, CESI"></label><label>Routine Tests / 例行试验<input name="routineTests" data-advanced placeholder="Manufacturer standard or specified"></label><label>Type / Special Tests / 型式或特殊试验<input name="typeSpecialTests" data-advanced placeholder="Temperature rise, impulse, sound, short-circuit"></label><label>Required Documents / 文件要求<input name="documents" data-advanced placeholder="GA drawing, test report, manual, datasheet"></label><label>Language / 文件语言<select name="documentLanguage" data-advanced><option value="">Not specified</option><option>English</option><option>Chinese</option><option>Other</option></select></label></div></div>
              <div class="technical-group"><h3>7. Accessories & Monitoring / 附件与监测</h3><div class="checkbox-row"><label><input type="checkbox" name="accessories" value="Buchholz Relay" data-advanced>Buchholz Relay</label><label><input type="checkbox" name="accessories" value="Pressure Relief Device" data-advanced>Pressure Relief</label><label><input type="checkbox" name="accessories" value="Oil Level Indicator" data-advanced>Oil Level</label><label><input type="checkbox" name="accessories" value="Winding Temperature Indicator" data-advanced>WTI</label><label><input type="checkbox" name="accessories" value="Oil Temperature Indicator" data-advanced>OTI</label><label><input type="checkbox" name="accessories" value="Fans" data-advanced>Fans</label><label><input type="checkbox" name="accessories" value="Surge Arrester" data-advanced>Surge Arrester</label><label><input type="checkbox" name="accessories" value="Cable Box" data-advanced>Cable Box</label><label><input type="checkbox" name="accessories" value="Digital Monitoring" data-advanced>Digital Monitoring</label><label><input type="checkbox" name="accessories" value="Not Sure" data-advanced>Not Sure</label></div></div>
              <div class="technical-group"><h3>8. Commercial, Packing & Delivery / 商务、包装与交付</h3><div class="rfq-grid"><label>Incoterms / 贸易条款<select name="incoterms" data-advanced><option value="">Not specified</option><option>EXW</option><option>FOB</option><option>CFR</option><option>CIF</option><option>DAP</option><option>DDP</option><option>Not Sure</option></select></label><label>Destination Port / 目的港<input name="destinationPort" data-advanced placeholder="e.g. Los Angeles, Hamburg"></label><label>Expected Delivery Time / 期望交期<input name="deliveryTime" data-advanced placeholder="e.g. 10 weeks after drawing approval"></label><label>Packing Requirement / 包装要求<input name="packingRequirement" data-advanced placeholder="Seaworthy package, wooden case, etc."></label><label class="full">Other Requirements / 其他要求<textarea name="otherRequirements" rows="4" data-advanced placeholder="Any missing information, site conditions, replacement constraints, tender clauses, or technical questions."></textarea></label></div></div>
            </details>
          </div>
        </section>
        <section class="rfq-step"><p class="eyebrow">Step 4</p><h2>Review & Submit / 摘要确认并提交</h2><p class="source-note">Prototype only. Connect this form to email, CRM or backend before launch.</p><button class="btn btn-primary" type="submit">Submit RFQ for Engineering Review</button></section>
      </form>
      <aside class="summary-card" data-summary><p class="eyebrow">Live Summary</p><h2>Inquiry Summary</h2><p>Selection will appear here.</p></aside>
    </section>
  </main>
  <footer class="footer"><div class="footer-grid"><div><h2>Tianyu Electric</h2><p>Transformer-focused B2B website first version.</p></div><div><h3>Products</h3><a href="products.html">Transformer Products</a><a href="rfq.html">Guided RFQ Selector</a></div><div><h3>Applications</h3><a href="applications.html">Applications & Projects</a></div><div><h3>Company</h3><a href="about.html">About Us</a><a href="contact.html">Contact</a></div></div><div class="footer-bottom"><span>© 2026 Tianyu Electric</span><a href="privacy.html">Privacy Policy</a></div></footer>
  <script>
    var form=document.querySelector('[data-rfq-form]'),summary=document.querySelector('[data-summary]'),panels=[].slice.call(document.querySelectorAll('[data-panel]'));
    function value(name){return form.elements[name]&&form.elements[name].value?form.elements[name].value:'Not specified'}
    function radio(name){var item=form.querySelector('input[name="'+name+'"]:checked');return item?item.value:'Not specified'}
    function checks(name){return [].slice.call(form.querySelectorAll('input[name="'+name+'"]:checked')).map(function(x){return x.value}).join(', ')||'Not specified'}
    function advancedCount(){var items=[].slice.call(form.querySelectorAll('[data-advanced]'));var filled=items.filter(function(x){return x.type==='checkbox'?x.checked:!!x.value}).length;return filled+' advanced fields filled, '+(items.length-filled)+' left blank or to be confirmed'}
    function refresh(){var selected=(form.querySelector('input[name="productStructure"]:checked')||{}).dataset?.structure||'liquid';panels.forEach(function(p){p.hidden=p.dataset.panel!==selected});var structure=selected==='liquid'?[value('insulatingLiquid'),value('tankStructure'),value('liquidCooling')].join(' | '):selected==='dry'?[value('dryInsulation'),value('coreMaterial'),value('enclosureType'),value('dryCooling')].join(' | '):'Future module, engineering review required';var rows=[['Product Structure',radio('productStructure')],['Voltage Direction',value('voltageTransformation')],['Application',value('applicationScenario')],['Engineering Role',value('engineeringRole')],['Special Requirements',checks('specialRequirement')],['Structure Details',structure],['Basic Parameters',[value('ratedCapacity'),value('primaryVoltage'),value('secondaryVoltage'),value('frequency'),value('phase')].join(' | ')],['Installation & Country',[value('installation'),value('country')].join(' | ')],['Technical Table',advancedCount()]];summary.innerHTML='<p class="eyebrow">Live Summary</p><h2>Inquiry Summary</h2><dl>'+rows.map(function(r){return '<dt>'+r[0]+'</dt><dd>'+(r[1]||'Not specified')+'</dd>'}).join('')+'</dl>'}
    form.addEventListener('input',refresh);form.addEventListener('change',refresh);form.addEventListener('submit',function(e){e.preventDefault();alert('RFQ captured for prototype review. Connect this form to email or CRM before launch.')});refresh();
  </script>
</body>
</html>`;
}
